# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2c8166b075d507c2cdb5eca793389c77d344ee6a9e1c33168c876ab01c75a7ff9e3eb2edb8e1ff04004d3c04eeaf1434e396a108fd704cfd3eb481fe3fa9db

test:
  secret_key_base: 0387d6b7dadc6c48c4523a460cf35301cb9513268d7d697df0fb0fc794b7d1e6bce7d64a89dc926f6c9eef189fd30435b9b48044ff659df6a02c140a3fe1e72d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
